### ISSUE TITLE
Hosting on google drive

### ISSUE THREAD

**Issue by David-Bates** [cgvirus/Optical-Flare-Node-For-Blender-Compositor#1]
Why do you have a github repo that only links to google drive to download the nodes?

Why not just have the blend and assets in the repo here? Then you can link to the [repo download zip](https://github.com/cgvirus/Optical-Flare-Node-For-Blender-Compositor/archive/master.zip) as your archive.

**Comment by cgvirus** [comment]
I tried and Blender looses the the file path data blocks..
